### ISSUE TITLE
Like -feature is throwing js exceptions

### ISSUE THREAD

**Issue by artur-gajewski** [Cobase/cobase#113]
It seems that something broke the functionality of Like -feature. When you click on the like number, the user list is not showing up and javascript is throwing exception.

**Comment by artur-gajewski** [comment]
@stiggg can you double check that the commenting feature didn't break this?

**Comment by stiggg** [comment]
Ok, I'll check that.

**Comment by stiggg** [comment]
Ok it wasn't me, but I fixed it anyway. See my PR #114 for a fix.
