### ISSUE TITLE
Post "like/unlike" feature

### ISSUE THREAD

**Issue by artur-gajewski** [Cobase/cobase#13]
Add link to like/unlike into post and mouseover to display users who like the specific post

**Comment by janimattiellonen** [comment]
I'm taking this! Still cannot assign it to myself.

**Comment by janimattiellonen** [comment]
I was thinking that this could be implemented in a way so that it would be easy (with very little extra code) to add the like/unlike feature to pretty much any entity.

Similar to how FabienPennequin/DoctrineExtensions-Taggable is implemented.

**Comment by artur-gajewski** [comment]
Sounds very good!

**Comment by artur-gajewski** [comment]
Issue merged.
