### ISSUE TITLE
Link to info about a people

### ISSUE THREAD

**Issue by HeikkiNaski** [Cobase/cobase#15]
I suspected that Morgan Freeman was not actually the Morgan Freeman and wanted to find out. There was no link on the name, so I navigated to the People-section. It only had Latest users there so I could not check Morgan or his other posts.

I was not able to see what else Morgan had posted and whether his real name was Morgan.

I'll be tossing and turning many a night because of this.

**Comment by artur-gajewski** [comment]
User info page implemented. When you click on user's name on a post, a page opens up with list of posts and groups that user has created.
