### ISSUE TITLE
Creating a new group fails

### ISSUE THREAD

**Issue by janimattiellonen** [Cobase/cobase#21]
Error: Variable "subscriptions" does not exist in ::base.html.twig at line 130 

Additionally the for loop starting on line 128 looks weird as it has an else clause directly after.

**Comment by artur-gajewski** [comment]
What action causes this error?

**Comment by janimattiellonen** [comment]
See https://github.com/CoBase/cobase/issues/7#issuecomment-20226382 (in the for loop) Missing null check?

**Comment by artur-gajewski** [comment]
This seems to be fixed.
