### ISSUE TITLE
Creating a bookmarklet to easily save some text or an url

### ISSUE THREAD

**Issue by gbonifaceNative** [Cobase/cobase#66]
Hello,

It would be great to think about a bookmarklet to allow users to save text or url in a message in a group.

Maybe when can embed a page like `http://cobase.url/post/new` and automatically fill the content of the update with the selected text or if there is nothing selected with the current url.

The user will have to choose in which group he wants to save the update and submit the form.

I can help on that if needed.

**Comment by artur-gajewski** [comment]
Sounds like a great idea. So in short, there should be one field for the URL and user copy/pastes a URL to this box, after which app gets the content from the URL and places it into the new post's update field.

Then there should be a pull-down for all public groups to which the new post will be saved to.

Did I understand you correctly?

**Comment by gbonifaceNative** [comment]
Hello,

Your idea is a bit different of mine but sounds interesting and can be the best I think.

One thing I see is that it will be important to fetch only important data on the url and not ads or things like that...

**Comment by artur-gajewski** [comment]
http://demo.shubhamtipstricks.com/extracturl/index.php

This is what I was thinking of. The images can be left out, only the content is important. Perhaps the title and n amount of lines from the content is enough?

**Comment by artur-gajewski** [comment]
Bt the way, we can discuss about this on IRC, channel is #cobase @ freenode.net

**Comment by gbonifaceNative** [comment]
One thing that coul be really cool is that the bookmarklet automatically fetch the data and put it in the textarea so that the user can just submit the form.

But maybe there will be some javascript issues with cross-scripting... :(

**Comment by wysow** [comment]
So PR will follow...

**Comment by wysow** [comment]
So we can close this one, see #69
