### ISSUE TITLE
Upgrade to Symfony 2.3.1

### ISSUE THREAD

**Issue by artur-gajewski** [Cobase/cobase#7]
Upgrade Symfony to version 2.3.1

Also composer.json needs to be updated.

**Comment by janimattiellonen** [comment]
I have a somewhat working version of cobase using sf 2.3 allthough some pages do not work due to some errors in the base.html.twig file. Also some tests fail die to old code. I'll hopefully push the sf 2.3 update tomorrow (saturday).

**Comment by artur-gajewski** [comment]
Have a look at mergeVariables() function in controllers. Some action might return render without it, thus causing the error. The mergeVariables() merges action specific view variables woth those of needed for every single page. Not sure if this is correct way to implement such feature, feel free to comment.

**Comment by janimattiellonen** [comment]
This looks very weird to me. The first claus is a {% for .... %}

end after it  a {% else %}
![screenshot](https://f.cloud.github.com/assets/1076448/725688/013ce4a6-e095-11e2-89cf-b853823bf93f.jpg)

**Comment by artur-gajewski** [comment]
It is valid twig syntax. If the array has zero items, it will go into else section ;-)

**Comment by janimattiellonen** [comment]
Ok. The programmer inside me cringed a bit ;)

Then the problem is most likely a missing null check...
