### ISSUE TITLE
Bookmarklet not working on some websites

### ISSUE THREAD

**Issue by artur-gajewski** [Cobase/cobase#83]
On some websites, injecting javascript into DOM is not working and console gives exceptions.

Example: http://www.tietoviikko.fi/kaikki_uutiset/article922002.ece

**Comment by artur-gajewski** [comment]
Uncaught TypeError: Object function (a,b){return new c.fn.init(a,b)} has no method 'type' jquery.fancybox.pack.js:7
(anonymous function) jquery.fancybox.pack.js:7
c.extend.each jquery-1.4.2.js:30
f.extend.open jquery.fancybox.pack.js:7
f.fancybox jquery.fancybox.pack.js:2
loadCobase bookmarklet.js:28

**Comment by wysow** [comment]
That's because this site already loads an older version of jquery that do not work with fancybox...

I don't really know which is the best way to handle this...

**Comment by artur-gajewski** [comment]
You mean Tietoviikko.fi is using different version from what you need to be using?

**Comment by wysow** [comment]
Yes that's what I mean...

**Comment by wysow** [comment]
Maybe the solution is to find a way to delete old jquery versions on the website, adding cobase one and after the save of the post, delete all cobase files from the html and retrieve old version of jquery...

@artur-gajewski What do you think about that ?

**Comment by artur-gajewski** [comment]
Yes I believe that would be an option. Go ahead and try that.

**Comment by artur-gajewski** [comment]
@wysow, any update on this? Did the jQuery version replacement work?

**Comment by wysow** [comment]
More time to work on this in the next days, stay tuned... ;)

**Comment by wysow** [comment]
Fixed bookmarklet is here : https://github.com/CoBase/cobase/pull/108
