### ISSUE TITLE
Vagrant gives errors

### ISSUE THREAD

**Issue by artur-gajewski** [Cobase/cobase#85]
When entering 'vagrant up', first I got following output. My setup is OS X.

host-001:cobase artur$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Box 'precise64' was not found. Fetching box from specified URL for
the provider 'virtualbox'. Note that if the URL does not have
a box for this provider, you should interrupt Vagrant now and add
the box yourself. Otherwise Vagrant will attempt to download the
full box prior to discovering this error.
Downloading or copying the box...
Extracting box...te: 744k/s, Estimated time remaining: --:--:--)
Successfully added box 'precise64' with provider 'virtualbox'!
[default] Importing base box 'precise64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] VM booted and ready for use!
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /tmp/vagrant-puppet/manifests
[default] -- /tmp/vagrant-puppet/modules-0
[default] Exporting NFS shared folders...
Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
[default] Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -o udp,vers=3 192.168.33.1:'/Users/artur/workspace/cobase' /vagrant
Stdout from the command:
Stderr from the command:
stdin: is not a tty
mount.nfs: Connection timed out

**Comment by artur-gajewski** [comment]
It seems I had to add the following to Vagran't .profile file:

if `tty -s`; then
   mesg n
fi

Then I went to do vagrant provision it seems to go to finish the installation, but then in ssh I can't find the project files anywhere.

**Comment by erikaheidi** [comment]
Artur, It seems to be something related to the NFS shared folders. Could you please increase the debug level, by setting this environment variable:

`VAGRANT_LOG=INFO`

before running vagrant up / reload ?

Then you check for the messages shown when it reaches this part "[default] Mounting NFS shared folders..." . It will show more information, so we will probably find a better error message.

**Comment by artur-gajewski** [comment]
I got it to work. Apparently the box installed didn't have guest additions. I tried to set the box which is Ubuntu 12.04 LTS and includes guest additions and now it is working.

I modified the following and Vagrant started working:

config.vm.box = "precise64-guest-additions"
config.vm.box_url = "http://dl.dropbox.com/u/1537815/precise64.box"

**Comment by artur-gajewski** [comment]
Pull Request: https://github.com/CoBase/cobase/pull/86

**Comment by wysow** [comment]
Problem for me on this :

```
Downloading or copying the box...
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 509 Bandwidth Error
```

**Comment by erikaheidi** [comment]
This error happens when it cannot find the box url provided - apparently this custom box is always running out of bandwith.

Please try using the clean ubuntu box, by editing your Vagrantfile and changing the "config.vm.box_url"

`config.vm.box_url = "http://files.vagrantup.com/precise64.box"`

@artur-gajewski for the guest additions problem, we can just run the following command:

`vagrant plugin install vagrant-vbguest`

And it will be installed, is a default vagrant plugin now, no need to do any extra step. 

I will make some changes to improve the performance, then I can change it back to this clean box.

**Comment by wysow** [comment]
@erikaheidi thanks for the tip, I've found that too... Will try and say if everything works great.

**Comment by artur-gajewski** [comment]
@erikaheidi I re-opened this issue, make your changes and send a PR when you get time ;)

**Comment by artur-gajewski** [comment]
@erikaheidi I just reverted to the original box url you provided and merged it with master branch.
